<template>
    <v-dialog :value="value" @input="$emit('input', $event)" persistent :fullscreen="$vuetify.breakpoint.mobile">
        <pre-loader v-show="Loader"></pre-loader>
        <v-card class="right-fixed-panel pl-3 v-scrolling-div" :width="$vuetify.breakpoint.mdAndUp ? '70vw' : ''">
            <v-container class="px-2 d-flex flex-column">
                <!-- Top Row -->
                <v-row class="align-center">
                    <v-btn icon class="my-auto ml-3"
                        @click="tab == 'tab-payments' ? (tab = 'tab-analysis') : (tab = 'tab-details')">
                        <v-icon>
                            mdi-arrow-left
                        </v-icon>
                    </v-btn>
                    <v-col cols="4" class="d-flex flex-column pl-0 my-auto">
                        <h3>{{ DialogHeader }}</h3>
                        <p class="mb-0">Please enter the details of the outcome.</p>
                    </v-col>
                    <v-col cols="7">
                        <v-tabs fixed-tabs v-model="tab">
                            <v-tab :ripple="false" href="#tab-details">Details</v-tab>
                            <v-tab :ripple="false" href="#tab-analysis">Physical Progress</v-tab>
                        </v-tabs>
                    </v-col>
                    <v-btn @click="unloadCreateOutput()" icon>
                        <v-icon>mdi-close</v-icon>
                    </v-btn>
                </v-row>

                <!-- View  -->

                <v-card-text class="mb-auto">
                    <v-tabs-items v-model="tab">
                        <v-tab-item value="tab-details">
                            <v-container>
                                <v-form ref="detailsForm">
                                    <v-row>
                                        <v-col cols="10">
                                            <v-text-field label="Outcome/ Activity ID (Auto Generated)"
                                                v-model="autoGeneratedActivityId" readonly outlined />
                                        </v-col>
                                        <v-col cols="10">
                                            <v-text-field :rules="alphanumericRules" label="Outcome/ Activity Name *"
                                                v-model="activityName" outlined />
                                        </v-col>
                                        <v-col cols="10">
                                            <v-textarea :rules="requiredRule" v-model="activityDescription"
                                                label="Outcome/ Activity Description" outlined />
                                        </v-col>

                                    </v-row>
                                    
                                        <v-col cols="10" class="d-flex">
                                            <div class="d-flex">
                                                <v-card-subtitle>Start Date :</v-card-subtitle>
                                                <v-btn id="startDatePickerBtn" height="60"
                                                    @click="startDateToggle = !startDateToggle">
                                                    <template v-if="startDate">
                                                        {{ cStartDate[1]}} <br> {{`${cStartDate[0]} ${cStartDate[2]}`}}
                                                    </template>
                                                    <template v-else>
                                                        Select
                                                    </template>
                                                </v-btn>
                                                <v-date-picker v-model="startDate" v-if="startDateToggle"
                                                    @input="startDateToggle = false" no-title class="ml-2">
                                                </v-date-picker>
                                            </div>
                                            <div class="d-flex">
                                                <v-card-subtitle>End Date :</v-card-subtitle>
                                                <v-btn id="endDatePickerBtn" height="60"
                                                    @click="endDateToggle = !endDateToggle">
                                                    <template v-if="endDate">
                                                        {{ cEndDate[1]}} <br> {{ cEndDate[0]}} {{ cEndDate[2]}}
                                                    </template>
                                                    <template v-else>
                                                        Select
                                                    </template>
                                                </v-btn>
                                                <v-date-picker v-model="endDate" :min="startDate" v-if="endDateToggle"
                                                    @input="endDateToggle = false" no-title class="ml-2">
                                                </v-date-picker>
                                            </div>
                                        </v-col>
                                        <v-col cols="10">
                                            <v-text-field :rules="[v => v > 0 || 'Please select the start and end dates']"
                                                v-model="cWeightageValue" label="Weightage/ Duration (Auto calculated)"
                                                placeholder="30" outlined readonly />
                                        </v-col>
                                        <v-col class="mb-0" cols="10">
                                            <v-text-field :rules="alphanumericRules" v-model="activityUnit"
                                                label="Unit of measurement (UOM)" placeholder="Enter Unit" outlined />
                                        </v-col>
                                        <v-col cols="10" class="ma-0 pa-0 mb-1 pb-1 d-flex justify-space-between">
                                            <v-card-subtitle class="my-auto">Target Frequency(Monthly)</v-card-subtitle>
                                            <v-switch inset color="blue" v-model="monthlyTarget"></v-switch>
                                        </v-col>
                                        <!-- <v-row v-if="monthlyTarget"> -->
                                        <!-- <v-col v-if="monthlyTarget" cols="10" class="d-flex" style="overflow-x: scroll;overflow-y: visible; "> -->
                                        <v-col v-if="monthlyTarget && startDate && endDate && activityName" cols="10"
                                            class="d-flex wrap-table mb-12">

                                            <table class="output-table" border="1" ref="DataGrid"
                                                style="table-layout: fixed ; border-collapse: collapse; width: max-content">
                                                <thead>
                                                    <tr class="month_tr">
                                                        <th rowspan="2" class="sticky-col">Outcome</th>

                                                        <template v-for="(head, hid) in cHeaders">

                                                            <th class="text-center" rowspan="1" colspan="1" :key="hid">
                                                                {{ head.monthYear }}</th>
                                                        </template>
                                                    </tr>
                                                    <tr>
                                                        <template v-for="(head, hid) in cHeaders">
                                                            <!-- <template v-if="head.hasSubHeaders"> -->
                                                            <th class="text-center" :key="hid">Target</th>
                                                        </template>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td class="sticky-col "><v-text-field readonly class="td-text1"
                                                                solo flat hide-details
                                                                v-model="activityName"></v-text-field></td>
                                                        <template v-for="(head, hid) in cHeaders">
                                                            <!-- <template v-if="head.hasSubHeaders" > -->
                                                            <td class="text-center" :key="hid"><v-text-field
                                                                    :rules="numericRules" v-model="head.target"
                                                                    class="td-text" hide-details solo flat>
                                                                </v-text-field></td>

                                                            <!-- </template>  -->


                                                        </template>
                                                    </tr>
                                                </tbody>
                                            </table>

                                        </v-col>
                                        <template v-if="monthlyTarget">
                                            <v-col cols="10" class="pt-2">
                                                <v-text-field v-model="cactivityTarget" readonly
                                                    label="Activity Target(Fill all Target cells to auto-calculate)"
                                                    placeholder="10,0000" outlined />
                                            </v-col>
 
                                        </template>
                                        <template v-if="monthlyTarget == false">
                                            <v-col cols="10" class="pt-2">
                                                <v-text-field :rules="numericRules" v-model="activityTarget"
                                                    label="Activity Target" placeholder="10,0000" outlined />
                                            </v-col>
                                        </template>
                                        <v-col cols="10" class="pt-2">
                                            <v-select  v-model="sdg" placeholder="Select SDG"
                                            :items="sdgList"
                                            item-value="SDGID" 
                                             outlined  
                                            >
                                            <template v-slot:selection="{ item, index }">
                                                <v-avatar tile size="50" class=" mr-4"><img class="sdgImage" :src="require('@/assets/SDG_Icons/'+item.SDGImage)"></v-avatar>{{ item.SDG_Name }}</template>
                                            <template v-slot:item="{ item }">
                                                 <v-avatar tile size="50" class="mt-1 mr-4"><img :src="require('@/assets/SDG_Icons/'+item.SDGImage)" alt="SDG"></v-avatar>{{ item.SDG_Name }}</template>

                                            </v-select>

                                        </v-col>
                                        <!-- </v-row> -->
                                </v-form>
                            </v-container>
                        </v-tab-item>

                        <v-tab-item value="tab-analysis">
                            <v-container>
                                <v-form ref="physicalForm">
                                    <!-- <v-row justify="center" width="100%">
                      <div id="analysis-tabs-wrapper">
                          <v-tabs centered hide-slider background-color="transparent" v-model="subtab">
                              <v-tab class="mx-2" active-class="analysis-tab" :ripple="false" href="#quantitative">Quantitative Survey</v-tab>
                              <v-tab :disabled="true" class="mx-2" active-class="analysis-tab" :ripple="false" href="#qualitative">Qualitative Survey</v-tab>
                          </v-tabs>
                      </div>
                  </v-row>

                  <v-tabs-items v-model="subtab">
                      <v-tab-item value="quantitative"> -->
                                    <!-- Survey Section -->
                                    <v-row>
                                        <v-col cols="12">
                                            <p class="mb-0 px-1">Select Surveys join data's</p>
                                            <div class="d-flex align-center">
                                                <v-autocomplete v-model="selectedSurveyList" :items="SurveyList"
                                                    :item-text="z => z.SurveyName" :item-value="z => z.SurveyID"
                                                    multiple chips outlined dense placeholder="Select multiple surveys"
                                                    return-object>
                                                </v-autocomplete>
                                                <v-btn tile depressed color="green" class="ml-1" text :ripple="false"
                                                    @click="selectedSurveyList.length && (addSection = true), getSectionCollection()">+
                                                    Add Selection</v-btn>
                                            </div>
                                        </v-col>
                                        <v-col cols="12" v-if="addSection">
                                            <v-card-subtitle class="py-1" v-for="(item, index) in selectedSurveyList"
                                                :key="index">
                                                <v-hover v-slot="{ hover }" open-delay="100">
                                                    <v-card-subtitle class="pa-0 ma-0 my-1">
                                                        <span v-show="hover">
                                                            <v-btn x-small color="red"
                                                                @click="selectedSurveyList.splice(index, 1)"
                                                                :ripple="false" icon>
                                                                <v-icon small class="mr-2">mdi-close</v-icon>
                                                            </v-btn>
                                                        </span>
                                                        {{ item.SurveyName }}
                                                    </v-card-subtitle>
                                                </v-hover>
                                            </v-card-subtitle>
                                        </v-col>
                                    </v-row>

                                    <!-- Filter Sections -->

                                    <v-row class="d-flex flex-column mt-2">
                                        <p class="px-1 mb-2">Select filter conditions on selected surveys</p>
                                        <v-row class="section-headers-wrapper justify-space-between align-center">
                                            <v-col cols="4" class="py-0 text-center">Select question under
                                                section</v-col>
                                            <v-col cols="3" class="py-0 text-center">Define logic between them</v-col>
                                            <v-col cols="4" class="py-0 text-center">Options under Selected
                                                question</v-col>
                                            <v-col cols="1"> </v-col>
                                        </v-row>
                                        <v-row>
                                            <v-col cols="4">
                                                <v-select outlined dense label="Select Data Header" v-model="sectionID"
                                                    :items="cSelectSectionList" item-text="SectionName"
                                                    item-value="SectionId" :menu-props="{ bottom: true, offsetY: true }">
                                                    <template v-slot:prepend-item>
                                                        <v-list-item class="my-2">
                                                            <v-text-field hide-details prepend-inner-icon="mdi-magnify"
                                                                dense clearable flat outlined label="search"
                                                                v-model="selectDataSearch" />
                                                        </v-list-item>
                                                        <v-divider></v-divider>
                                                    </template>
                                                    <template v-slot:item="{ item, on }">
                                                        <v-list-item>
                                                            <v-menu transition="slide-y-transition" offset-x
                                                                open-on-hover open-delay="250">
                                                                <template v-slot:activator="{ on, attrs }">
                                                                    <v-btn text v-on="on" v-bind="attrs" block
                                                                        class="justify-space-between my-2">
                                                                        {{ item.SectionName }}
                                                                        <span>
                                                                            <v-icon color="blue">
                                                                                mdi-chevron-right
                                                                            </v-icon>
                                                                        </span>
                                                                    </v-btn>
                                                                </template>
                                                                <v-list>
                                                                    <v-list-item
                                                                        v-for="(Qitem, Qindex) in item.ProjectSurveySectionQuestionsList"
                                                                        :key="Qindex" v-on="on"
                                                                        @click="setQuestionSelection(Qitem, item)">
                                                                        {{ Qitem.QuestionName }}
                                                                    </v-list-item>
                                                                </v-list>
                                                            </v-menu>
                                                        </v-list-item>
                                                    </template>
                                                    <template v-slot:selection>
                                                        <p class="my-auto">{{
                                                            currentQuestion.QuestionName ?
                                                                currentQuestion.QuestionName : 'Select Data Header'
                                                        }}</p>
                                                    </template>
                                                </v-select>
                                            </v-col>
                                            <v-col cols="3">
                                                <v-autocomplete :disabled="!currentQuestion" outlined hide-details dense
                                                    label="Select Logic" :items="LogicItemsPrime" item-text="Type"
                                                    item-value="ID" return-object v-model="SurveyLogicPrime">

                                                </v-autocomplete>
                                            </v-col>

                                            <!-- Different Answer fields based on QuestionType -->
                                            <v-col cols="4">

                                                <v-text-field v-if="QuestionType == 0" outlined clearable hide-details
                                                    dense label="Answer" v-model="SurveyLogicPrimeAnswer" />

                                                <v-autocomplete v-if="QuestionType == 1" outlined dense hide-details
                                                    v-model="SurveyLogicPrimeAnswer" label="Select Answer"
                                                    :items="lstLogicAnswers" item-text="OptionValue"
                                                    item-value="OptionValue">
                                                </v-autocomplete>

                                                <v-menu v-if="QuestionType == 2" offset-y transition="scale-transition"
                                                    min-width="250">
                                                    <template v-slot:activator="{ on, attrs }">
                                                        <v-text-field v-model="SurveyLogicPrimeAnswer" outlined
                                                            prepend-inner-icon="mdi-calendar" v-on="on" v-bind="attrs"
                                                            dense hide-details readonly />
                                                    </template>
                                                    <v-date-picker v-model="SurveyLogicPrimeAnswer" no-title
                                                        format="DD-MM-YYYY">
                                                    </v-date-picker>

                                                </v-menu>

                                                <v-textarea v-if="QuestionType == 4" outlined dense
                                                    v-model="SurveyLogicPrimeAnswer" hide-details />
                                                <!-- implement Cascading Selection -->
                                                <!-- QuestionType == 3 -->
                                            </v-col>

                                            <v-col cols="1">
                                                <v-btn text color="green" class="ml-1"
                                                    @click="addFilterSection()">+</v-btn>
                                            </v-col>
                                        </v-row>

                                        <v-row class="d-flex flex-column">
                                            <p class="mb-2">Selected conditions and set logic between them</p>
                                            <v-col v-if="!currentFilterSections.length" cols="8"
                                                class="section-conditions-wrapper my-1 d-flex justify-space-between px-5 align-center">
                                                <p class="ma-0 pa-0">Selected Sections <span
                                                        class="mx-2"><v-icon>mdi-link</v-icon></span> Selected Question
                                                </p>
                                                <p class="ma-0 pa-0">Equal to</p>
                                                <p class="ma-0 pa-0">Output</p>
                                            </v-col>
                                            <template v-else v-for="(item, index) in currentFilterSections">
                                                <v-col :key="index" class="pa-1">
                                                    <v-hover v-slot="{ hover }" open-delay="150">
                                                        <div class="pa-0 ma-0 d-flex align-center">
                                                            <div class="section-conditions-subwrapper my-1 d-flex px-5 py-3 align-center justify-flex-start"
                                                                style="width: fit-content;">
                                                                <p class="ma-0 pa-0 mr-5 font-weight-medium">
                                                                    {{ item.Section.SectionName }} <span
                                                                        class="mx-2"><v-icon>mdi-link</v-icon></span>
                                                                    {{ item.Question.QuestionName }}</p>
                                                                <p class="ma-0 pa-0 mr-5 font-weight-medium">
                                                                    {{ item.Logic.Type }}</p>
                                                                <p class="ma-0 pa-0 mr-5 font-weight-medium">
                                                                    {{ item.Answer }}</p>
                                                            </div>
                                                            <v-btn icon :key="index" v-show="hover" class="ml-3"
                                                                @click="currentFilterSections.splice(index, 1)">
                                                                <v-icon color="red">
                                                                    mdi-delete-outline
                                                                </v-icon>
                                                            </v-btn>
                                                        </div>
                                                    </v-hover>
                                                    <v-col cols="2">
                                                        <v-select flat solo dense :items="lstConditions"
                                                            v-if="index < currentFilterSections.length-1"
                                                            item-text="OptionValue" item-value="OptionID" hide-details
                                                            return-object
                                                            @change="$emit('conditionChanged', item.FilterID)"
                                                            label="Select Condition"
                                                            v-model="item.condition"></v-select>
                                                    </v-col>
                                                </v-col>
                                            </template>
                                        </v-row>

                                        <!-- Summarize Actuals -->

                                        <v-row class="d-flex flex-column">
                                            <p class="mb-2">Summarize/Calculate actuals</p>

                                            <v-row class="section-headers-wrapper">
                                                <v-col cols="">
                                                    <v-select solo flat dense color="white"
                                                        placeholder="Pick a Mathematical Operation" :items="cLogicItems"
                                                        v-model="currentActualsLogic" item-text="Type" item-value="ID"
                                                        :menu-props="{ auto: true, offsetY: true }">
                                                        <template v-slot:prepend-item>
                                                            <v-list-item class="mb-2">
                                                                <v-text-field outlined dense label="Search"
                                                                    prepend-inner-icon="mdi-magnify"
                                                                    v-model="LogicItemsSearch" hide-details>

                                                                </v-text-field>
                                                            </v-list-item>
                                                            <v-divider></v-divider>
                                                        </template>
                                                    </v-select>
                                                </v-col>
                                                <v-col cols="">
                                                    <v-select v-model="additionalSection" solo flat dense color="white"
                                                       :disabled="currentActualsLogic==1"
                                                       clearable
                                                        :items="cAdditionalSectionList" item-text="SectionName"
                                                        item-value="SectionId" return-object
                                                        placeholder="Select Question Under Section"
                                                        :menu-props="{ auto: true, offsetY: true }">
                                                        <template v-slot:prepend-item>
                                                            <v-list-item class="my-2">
                                                                <v-text-field hide-details
                                                                    prepend-inner-icon="mdi-magnify" dense clearable
                                                                    flat outlined label="search"
                                                                    v-model="additionalSectionSearch" />
                                                            </v-list-item>
                                                            <v-divider></v-divider>
                                                        </template>
                                                        <template v-slot:item="{ item, on }">
                                                            <v-list-item>
                                                                <v-menu transition="slide-y-transition" offset-x
                                                                    open-on-hover open-delay="250">
                                                                    <template v-slot:activator="{ on, attrs }">
                                                                        <v-btn text v-on="on" v-bind="attrs" block
                                                                            class="justify-space-between my-2">
                                                                            {{ item.SectionName }}
                                                                            <span>
                                                                                <v-icon color="blue">
                                                                                    mdi-chevron-right
                                                                                </v-icon>
                                                                            </span>
                                                                        </v-btn>
                                                                    </template>
                                                                    <v-list>
                                                                        <v-list-item
                                                                            v-for="(Qitem, Qindex) in item.ProjectSurveySectionQuestionsList"
                                                                            :key="Qindex" v-on="on"
                                                                            @click="setAdditionalQuestionSelection(Qitem, item)">
                                                                            {{ Qitem.QuestionName }}
                                                                        </v-list-item>
                                                                    </v-list>
                                                                </v-menu>
                                                            </v-list-item>
                                                        </template>
                                                        <template v-slot:selection>
                                                            <p class="my-auto">
                                                                {{ currentAdditionalQuestion.QuestionName }}</p>
                                                        </template>
                                                    </v-select>
                                                </v-col>

                                                <!-- <v-col cols="">
                                                    <v-select v-model="currentComparison" :items="comparisonList"
                                                        item-text="name" item-value="id" solo flat dense color="white"
                                                        placeholder="Select Comparison"
                                                        :menu-props="{ auto: true, offsetY: true }">
                                                        <template v-slot:prepend-item>
                                                            <v-list-item class="mb-2">
                                                                <v-text-field outlined prepend-inner-icon="mdi-magnify"
                                                                    v-model="comparisonListSearch" hide-details
                                                                    label="Search" dense>
                                                                </v-text-field>
                                                            </v-list-item>
                                                            <v-divider></v-divider>
                                                        </template>
                                                    </v-select>
                                                </v-col> -->
                                            </v-row>

                                            <v-row class="d-flex ">
                                                <v-col cols="7">
                                                    <p class="mb-1 mt-2 px-1">Actual Value</p>
                                                    <v-text-field v-model="actualsValue" outlined
                                                        placeholder="Non Editable" dense persistent-hint readonly
                                                        hint="The actual value is derived based on the summarised formula applied"></v-text-field>

                                                </v-col>
                                                <v-col cols="2" align-self="center" @click="apply=1;validateFields();OutPutQuantitativeLogicList = []" class="pt-0">
                                                    <v-btn   depressed>Save & Apply</v-btn>

                                                </v-col>
                                            </v-row>

                                        </v-row>
                                    </v-row>

                                    <!-- </v-tab-item>
                  </v-tabs-items> -->
                                </v-form>
                            </v-container>
                        </v-tab-item>
                    </v-tabs-items>
                </v-card-text>
                <v-card-actions class="align-self-end">
                    <Success-Button title="Save & Complete" @click.native=validateFields()></Success-Button>

                </v-card-actions>
            </v-container>
        </v-card>
        <v-snackbar v-model="snackBarMsg.value" :color="snackBarMsg.color" top>
            {{ snackBarMsg.message }}
        </v-snackbar>
    </v-dialog>
</template>

<script>
import SuccessButton from "@/components/success-button.vue";
import PreLoader from '@/components/pre-loader.vue'
var objManageProjectActivity
async function importscript() {
    return Promise.all([
        import("@/BL/ManageProjectActivity.js").then((mod) => {
            objManageProjectActivity = new mod.ManageProjectActivity();
        }),
    ]);
}
export default {
    components: {
        SuccessButton,
        PreLoader,
        
    },
    props: ['value', 'editMode', 'editPayload', 'activityList', 'isSub'],
    data() {
        return {
            monthNames: ["Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
            Loader: false,
            WsID: this.$route.query.WsID,
            ProjectID: this.$route.query.ProjID,
            tab: 'tab-details',
            subtab: 'quantitative',
            activityType: 'Quantitative',
            activityID: 0,
            parentActivityID: 0,
            activityDescription: '',
            activityName: '',
            subActivities: false,
            monthlyTarget: false,
            startDate: '',
            endDate: '',
            monthList: '',
            startDateToggle: false,
            endDateToggle: false,
            activityUnit: '',
            activityTarget: '',
            totalBudget: '',
            subtab: null,
            addSection: false,
            selectedSurveyList: [],
            sectionID: '',
            sectionCollection: [],
            selectDataSearch: '',
            currentQuestion: null,
            currentQuestionParent: null,
            selectLogicSearch: '',
            QuestionType: 0,
            surveyResponseId:0,
            currentFilterSections: [],
            currentActualsLogic: '',
            additionalSectionSearch: '',
            additionalSection: '',
            currentAdditionalQuestion: null,
            currentAdditionalQuestionParent: null,
            currentComparison: 1,
            paymentLink: false,
            projectBudgetAmount: 0,
            headers: [],
            headers_edit: [],
            comparisonList: [
                {
                    id: 1,
                    name: 'Target'
                }
            ],
            listItems: [],
            unitCost: '',
            comparisonListSearch: '',
            LogicItemsSearch: '',
            currentQuestionPayload: [],
            autoGeneratedActivityId: 'OT...',
            actualsValue: 0,
            snackBarMsg: {
                value: false,
                message: '',
                color: '' // error or success
            },
            // 
            SurveyList: [],
            LogicItems: [],
            LogicItemsPrime: [],
            LogicItemsPrimeCopy: [],

            lstConditions: [
                {
                    OptionID: 1,
                    OptionValue: "AND"
                },
                {
                    OptionID: 2,
                    OptionValue: "OR"
                }
            ],

            DialogHeader: 'Create Activity',
            SurveyLogicPrime: '',
            SurveyLogicPrimeAnswer: '',
            OutPutQuantitativeLogicList: [],
            lstLogicAnswers: [],
            masterSectionCollection: [],
            sdgList: [],
            sdg:'',
            preImgUrl:'@/assets/SDG/',
            apply:0,
            requiredRule: [
                (v) => !!v || "Required field.",
            ],
            alphanumericRules: [
                (v) => !v || /^[ a-z0-9A-Z()_-]+$/.test(v) || "Please enter valid details",
                (v) => !!v || "Required field.",
            ],
            numericRules: [
                (v) => !v || /^[0-9]+$/.test(v) || "Please enter only numbers",
                (v) => !!v || "Required field.",
            ],
            numericRule: [
                (v) => !v || /^[0-9]+$/.test(v) || "Please enter only numbers",
            ],
            budjetRules: [
                (v) => !v || /^[0-9]+$/.test(v) || "Please enter only numbers",
                (v) => v > 0 || "Please enter a value greater than zero",
                (v) => !!v || "Required field.",
            ],
        }
    },
    async mounted() {
        await importscript()
        await this.fnGetProjectSurveyList();
        // await this.fnGetUsersListByGroupId();
        // await this.fnGetAllProjectTags();
        // await this.fnGetExpenseTagList();
        // await this.fnGetProjectWorkflowsList();
        // await this.fnGetPeriodicityList();
        await this.fnGetLogicType();
        await this.GetSDGdata();

        if (this.editMode) {
            await this.initializeEdit()
          //  await this.GetProjectActivityActualValues()
                this.DialogHeader = 'Edit Activity'
            
        }
        else {
            let { autoGeneratedId } = await objManageProjectActivity.GetUniqueOutputAutoGeneratedId(this.WsID, this.ProjectID)
            this.autoGeneratedActivityId = autoGeneratedId
        }
    },
    computed: {
        cStartDate() {
            let date = new Date(this.startDate).toLocaleString('default', { day: '2-digit', month: 'short', year: '2-digit' })
            return date.replace(',', '').split(' ')
        },
        cEndDate() {
            let date = new Date(this.endDate).toLocaleString('default', { day: '2-digit', month: 'short', year: '2-digit' })
            return date.replace(',', '').split(' ')
        },
        cSelectSectionList() {
            if (!this.selectedSurveyList || !this.selectedSurveyList.length) return []
            let data = []
            let surveyIdList = this.selectedSurveyList.map(x => x.SurveyID)
            this.masterSectionCollection.forEach((x) => {
                if (surveyIdList.includes(x.SurveyId)) {
                    data.push(...x.ProjectSurveySectionList)
                }
            })
            data = data.map(x => {
                return {
                    ...x,
                    ProjectSurveySectionQuestionsList: x.ProjectSurveySectionQuestionsList.filter(s => s.Type)
                }
            })

            if (this.selectDataSearch) {
                return this.data.filter(x => x.SectionName.includes(this.selectDataSearch))
            }
            else return data
        },
        cAdditionalSectionList() {
            if (!this.selectedSurveyList || !this.selectedSurveyList.length) return []
            let data = this.sectionCollection.map(x => {
                return {
                    ...x,
                    ProjectSurveySectionQuestionsList: x.ProjectSurveySectionQuestionsList.filter(s => s.Type && s.Type == 'Numeric')
                }
            })
            data = data.filter(x => x.ProjectSurveySectionQuestionsList.length)
            if (this.additionalSectionSearch) {
                return data.filter(x => x.SectionName.includes(this.additionalSectionSearch))
            }
            else return data
        },
        cComparisonList() {
            if (this.comparisonListSearch) {
                return this.comparisonList.filter(x => x.name.includes(this.comparisonListSearch))
            }

            else return this.comparisonList
        },

        cLogicItems() {
            if (this.LogicItemsSearch) {
                return this.LogicItems.filter(x => x.Type.includes(this.LogicItemsSearch))
            }

            else return this.LogicItems
        },

        cWeightageValue: {
            get() {
                if (!this.startDate || !this.endDate) {
                    return 0
                }
                if (this.startDate == this.endDate) {
                    this.snackBarMsg = {
                        message: "Start and End Dates cannot be same",
                        color: 'blue',
                        value: true
                    }

                    this.endDate = ''
                    return 0
                }

                if (this.startDate > this.endDate) {
                    this.snackBarMsg = {
                        message: "Start date must be before end Date",
                        color: 'blue',
                        value: true
                    }

                    this.startDate = ''
                    return 0
                }
                let t1 = new Date(this.startDate).getTime()
                let t2 = new Date(this.endDate).getTime()

                let tx = t2 - t1

                let txToDays = tx / (1000 * 60 * 60 * 24)

                this.weightageValue = Math.ceil(txToDays)

                return this.weightageValue
            },
            set(val) {
                this.weightageValue = val
            }
        },
        cHeaders() {
            this.headers = []

            if (this.startDate && this.endDate) {
                if (this.headers_edit && this.headers_edit.length) {
                    this.headers_edit.forEach(head => {

                        this.headers.push({
                            monthYear: this.monthNames[head.ActMonth].concat(" ", head.ActYear),
                            actMonth: head.ActMonth,
                            actYear: head.ActYear,
                            target: head.Target,
                            budget: head.Budget
                        });
                    })
                    this.headers_edit = []
                    return this.headers

                }
                else {
                    let sdate = new Date(this.startDate)
                    let edate = new Date(this.endDate)
                    sdate.setDate(1)
                    do {
                        this.headers.push({
                            monthYear: this.monthNames[sdate.getMonth() + 1].concat(" ", sdate.getFullYear().toString()),
                            actMonth: sdate.getMonth() + 1,
                            actYear: sdate.getFullYear(),
                            target: '',
                            budget: ''
                        })
                        sdate.setMonth(sdate.getMonth() + 1)

                    } while (sdate <= edate);
                    return this.headers
                }
                // return [...this.headers, ...data]
            }
        },
        cactivityTarget() {

            if (this.monthlyTarget == true) {
                this.activityTarget = this.headers.reduce((sum, nxt) => parseInt(sum) + parseInt(nxt.target), 0)
                if (isNaN(this.activityTarget)) {
                    return 0
                }
                else {
                    return this.activityTarget
                }
            }
        },
        ctotalBudget() {

            if (this.monthlyTarget == true) {
                this.totalBudget = this.headers.reduce((sum, nxt) => parseInt(sum) + parseInt(nxt.budget), 0)
                if (isNaN(this.totalBudget)) {
                    return 0
                }
                else {
                    return this.totalBudget
                }
            }
        },
    },
    methods: {
        async fnCreateActivity() {

            // set subActivity total weightage 

            if (this.activityList && this.activityList.length && this.activityID == 0) {
                if (this.activityList.find(x => x.ActivityName == this.activityName)) {
                    this.snackBarMsg.message = "ActivityName already exists, Please enter a new activity name."
                    this.snackBarMsg.color = "error"
                    this.snackBarMsg.value = true
                }
            }

            this.Loader = true

            let data = new FormData()
            data.append('ProjectID', this.ProjectID)
            data.append('ActivityId', this.activityID)
            data.append('OutcomeName', this.activityName)
            data.append('Description', this.activityDescription)
            data.append("StartDate", this.startDate);
            data.append("EndDate", this.endDate);
            data.append("ActualValue",this.actualsValue)
            data.append("SDGID",this.sdg)

        

            if (this.headers && this.headers.length && this.monthlyTarget) {
                for (var x = 0; x < this.headers.length; x++) {
                    data.append('lstProjectOutcomeMonthwiseData[' + x + '].ActivityID', this.activityID);
                    data.append('lstProjectOutcomeMonthwiseData[' + x + '].Target', this.headers[x].target);
                    data.append('lstProjectOutcomeMonthwiseData[' + x + '].Budget', 0);
                    data.append('lstProjectOutcomeMonthwiseData[' + x + '].ActMonth', this.headers[x].actMonth);
                    data.append('lstProjectOutcomeMonthwiseData[' + x + '].ActYear', this.headers[x].actYear);

                }
            }

            // if tags
            // data.append("ActivityTagsList", JSON.stringify(item.ActivityTags));
            data.append("DatacollectionType", this.activityType);
            // data.append("SurveyId", 0);
            if (this.activityType == 'Quantitative') {

                data.append("SurveyResponseId", this.surveyResponseId);
                data.append("SurveyLogic", this.currentActualsLogic);
                data.append("SurveyTarget", this.activityTarget ? this.activityTarget : 0);
                let i = 0


                if (this.OutPutQuantitativeLogicList && this.OutPutQuantitativeLogicList.length) {
                    for (i = 0; i < this.OutPutQuantitativeLogicList.length; i++) {
                        data.append('OutcomeQuantitativeLogic[' + i + '].QuestionId', this.OutPutQuantitativeLogicList[i].QuestionId);
                        data.append('OutcomeQuantitativeLogic[' + i + '].SectionId', this.OutPutQuantitativeLogicList[i].SectionId);
                        data.append('OutcomeQuantitativeLogic[' + i + '].SurveyId', this.OutPutQuantitativeLogicList[i].SurveyId);
                        data.append('OutcomeQuantitativeLogic[' + i + '].BeneficiaryTypeQstnID', this.OutPutQuantitativeLogicList[i].BeneficiaryTypeQstnID);

                        if (this.OutPutQuantitativeLogicList[i].SurveyPrimeLogic != null && this.OutPutQuantitativeLogicList[i].SurveyPrimeLogic != undefined && this.OutPutQuantitativeLogicList[i].SurveyPrimeLogic.length > 0) {
                            for (var k = 0; k < this.OutPutQuantitativeLogicList[i].SurveyPrimeLogic.length; k++) {
                                data.append('OutcomeQuantitativeLogic[' + i + '].lstSurveyPrimeLogic[' + k + '].SurveyLogicPrime', this.OutPutQuantitativeLogicList[i].SurveyPrimeLogic[k].SurveyLogicPrimeID);
                                data.append('OutcomeQuantitativeLogic[' + i + '].lstSurveyPrimeLogic[' + k + '].SurveyLogicPrimeAnswer', this.OutPutQuantitativeLogicList[i].SurveyPrimeLogic[k].SurveyLogicPrimeAnswer);
                                data.append('OutcomeQuantitativeLogic[' + i + '].lstSurveyPrimeLogic[' + k + '].SurveyLogicCondition', this.OutPutQuantitativeLogicList[i].SurveyPrimeLogic[k].SurveyLogicCondition);
                            }
                        }
                    }

                }


                // else {
                //     this.snackBarMsg.message = "Please select atleast One Survey Question"
                //     this.snackBarMsg.value = true
                //     this.snackBarMsg.color = 'error'
                //     this.Loader = false
                //     return
                // }
            }
            else {
                data.append("BeneficiaryTypeQuestionID", 0)
                data.append("SurveySectionId", 0);
                data.append("SurveyQuestionId", 0);
                data.append("SurveyResponseId", 0);
                data.append("SurveyLogic", this.currentActualsLogic);
                data.append("SurveyTarget", this.activityTarget ? this.activityTarget : 0);
                data.append("PaymentLinkedBudget", this.totalBudget);

            }

            data.append("IsPaymentLinked", this.paymentLink)
            if (this.paymentLink) {
                data.append("PaymentLinkedBudget", this.projectBudgetAmount);
                data.append("ExpenseTagsList", null);
                data.append("ExpenseTagsNotifyUsersList", null);
            }
            else {
                data.append("PaymentLinkedBudget", 0);
                data.append("ExpenseTagsList", null);
                data.append("ExpenseTagsNotifyUsersList", null);
            }

            data.append("WorkflowId", 0); // N.A
            data.append("Periodicity", 1); // N.A but Mandatory to set default value as 1.
            data.append("PeriodicityOnceDate", 0);
            data.append("PeriodicityWeek", 0);
            data.append("PeriodicityMonthDay", 0);
            data.append("PeriodicityMonth", 0);
            data.append("PeriodicityMonthDateDay", 0);
            data.append("ActivityUsersList", []);

            // newly added fields: Mandatory
            data.append("AdditionalSectionId",this.additionalSection == undefined ? 0 : this.additionalSection.SectionId == undefined ? 0 : this.additionalSection.SectionId);
            data.append("AdditionalQuestionId", this.currentAdditionalQuestion == null ? 0 : this.currentAdditionalQuestion.QuestionId);
            data.append("AdditionalQuestionType", true); // check if section or beneficiary
            data.append("AutoGeneratedActivityId", this.autoGeneratedActivityId)
            data.append("UnitOfMeasure", this.activityUnit)
            console.log(data)
            try {
                let result = await objManageProjectActivity.AddOutcome(data);
                if (result.Status == 'Unhandled Exception' || result.Status == 'PeriodicityFailed') {
                    throw new Error(result.message)
                }
                else if (result.Status == 'success') {
                    if(this.apply==0)
                    {
                    if (this.editMode) {
                        this.snackBarMsg = {
                            message: "Successfully Edited Activity",
                            color: 'success',
                            value: true,
                        }
                    }
                    else {
                        this.snackBarMsg = {
                            message: "Activity successfully Added",
                            color: "success",
                            value: true
                        }
                    }
                    this.$emit('updateActivityList')
                    setTimeout(() => {
                        this.unloadCreateOutput();
                    }, 2000);
                }
                else{
                    this.activityID=result.outcomeId
                    let res=await objManageProjectActivity.GetOutcomeActualValue(result.outcomeId)
                    if (res.Status=="Success") {
                        console.log(res.data)
                        this.actualsValue = res.data;
                        this.apply=0
                    } 
                    else {
                        this.snackBarMsg.message = "Failed to get actual values"; 
                        this.snackBarMsg.value = true;
                        this.snackBarMsg.color = 'error'
                    }
                    this.Loader=false
                }
                }

            } catch (error) {
                this.snackBarMsg = {
                    message: "Failed to add activity",
                    color: "error",
                    value: true
                }
                this.Loader = false
                console.error("Failed to Add Activity: " + error)          
            }

            this.OutPutQuantitativeLogicList = []
        },
        async getSectionCollection() {
            if (!this.selectedSurveyList.length) {
                return
            }

            this.sectionCollection = []

            try {
                let surveyIdList = this.selectedSurveyList.map(x => x.SurveyID)
                let { data } = await objManageProjectActivity.GetSurveyCollectionBySurveyIds(this.ProjectID, JSON.stringify(surveyIdList))
                if (!data || !data.length) {
                    throw new Error('Invalid Response')
                }
                else {

                    data.forEach(q => this.sectionCollection.push(...q.ProjectSurveySectionList))
                    this.sectionCollection = this.sectionCollection.map(x => {
                        return {
                            ...x,
                            ProjectSurveySectionQuestionsList: x.ProjectSurveySectionQuestionsList.filter(s => s.Type)
                        }
                    })
                    this.masterSectionCollection = data
                    // console.log(this.masterSectionCollection)
                }
                return
            } catch (error) {
                console.error(error)
            }
        },

        /// <summary>
        ///  fnGetProjectSurveyList :- Function used to fetch project survey list
        /// </summary>
        /// <param name=""></param>
        /// <returns> </returns>
        async fnGetProjectSurveyList() {
            let result = await objManageProjectActivity.GetProjectSurveyList(this.ProjectID);
            if (result.status == "Unhandled Exception") {
                this.$router.push({ name: "error" });
            } else if (result.data) {
                // this.filterPaymentList = result.data;
                this.SurveyList = result.data;
            } else {
                this.snackBarMsg.message = "Failed to get survey list of Project"; // add project name here
                this.snackBarMsg.value = true;
                this.snackBarMsg.color = 'error'
            }
        },

        /// <summary>
        ///  fnGetLogicType :- Function used to fetch logic type
        /// </summary>
        /// <param name=""></param>
        /// <returns> </returns>
        async fnGetLogicType() {
            let result = await objManageProjectActivity.GetLogicType();
            if (result.status == "Unhandled Exception") {
                this.$router.push({ name: "error" });
            } else if (result.data) {
                if (result.data != null && result.data != undefined) {
                    // console.log(result.data)
                    this.LogicItems = result.data.filter(x => x.IsPrimeLogic == false);
                    this.LogicItemsPrime = result.data.filter(x => x.IsPrimeLogic == true);
                    this.LogicItemsPrimeCopy = result.data.filter(x => x.IsPrimeLogic == true);

                }
            }
        },

        async GetProjectActivityActualValues() {
            let result = await objManageProjectActivity.GetOutcomeActualValue(this.activityID);
            if (result.Status=="Success") {
                console.log(result.data)
                // this.filterPaymentList = result.data;
                this.actualsValue = result.data;
            } 
            else {
                this.snackBarMsg.message = "Failed to get actual values"; // add project name here
                this.snackBarMsg.value = true;
                this.snackBarMsg.color = 'error'
            }
        },
        async GetSDGdata(){
            let result=await objManageProjectActivity.GetSDGListForOutcome()
            if(result.status=="Success"){
                this.sdgList=result.data
            }

            else{
                this.snackBarMsg.message = "Failed to get SDG data"; 
                this.snackBarMsg.value = true;
                this.snackBarMsg.color = 'error'

            }
            
        },


        // function to prepopulate the fields inorder to edit the activity
        async initializeEdit() {
            console.log(this.editPayload)
            let {
                ActivityId,
                ActivityName,
                AdditionalQuestionId,
                AdditionalQuestionType,
                AdditionalSectionId,
                AdditionalSurveyQuestionId,
                AutoGeneratedActivityId,
                BeneficiaryTypeID,
                BeneficiaryTypeQuestionID,
                Description,
                StartDate,
                EndDate,
                IsPaymentLinked,
                OutcomeQuantitativeLogic,
                ParentActivityId,
                PaymentLinkedBudget,
                Progress,
                SurveyLogic,
                SurveyTarget,
                WeightagePercentage,
                UnitOfMeasure,
                lstProjectOutcomeMonthwiseData,
                ActualValue,
                SDGID

            } = this.editPayload

            // Commented the code for now - Getting the error 'Old Output'' as the additional question and additional section will be always null 
            // for the retrospective cases

            //if([AdditionalSectionId, AdditionalQuestionId ].some(x => !x || !parseInt(x))) {
            //  this.snackBarMsg.message = 'Old Output'
            //  this.snackBarMsg.color = 'error'
            //  this.snackBarMsg.value = true
            //  setTimeout(() => {
            //    this.unloadCreateOutput()
            //  }, 2000);
            //  return
            //}
            this.activityID = ActivityId
            this.parentActivityID = ParentActivityId
            this.activityName = ActivityName
            this.activityDescription = Description
            this.autoGeneratedActivityId = AutoGeneratedActivityId
            this.paymentLink = IsPaymentLinked
            this.projectBudgetAmount = PaymentLinkedBudget
            this.totalBudget = PaymentLinkedBudget
            this.startDate = (StartDate !== "0001-01-01T00:00:00") ? StartDate : ''
            this.endDate = (EndDate !== "0001-01-01T00:00:00") ? EndDate : ''
            this.activityTarget = SurveyTarget
            this.currentActualsLogic = SurveyLogic
            this.weightageValue = WeightagePercentage
            this.activityUnit = UnitOfMeasure
            this.actualsValue=ActualValue
            this.sdg=SDGID
            let surveyIdList = OutcomeQuantitativeLogic.map(x =>  x.SurveyId  )
            this.headers_edit = lstProjectOutcomeMonthwiseData
            if (this.headers_edit && this.headers_edit.length) {
                this.monthlyTarget = true
            }


            this.selectedSurveyList = this.SurveyList.filter(x => {
                if (surveyIdList.includes(x.SurveyID)) {
                    return x
                }
            })

            await this.getSectionCollection()
            if (this.sectionCollection.length) {
                if (AdditionalSectionId >= 1) {
                    this.additionalSection = this.sectionCollection.find(x => x.SectionId == AdditionalSectionId)


                    this.currentAdditionalQuestionParent = this.additionalSection
                    this.currentAdditionalQuestion = this.additionalSection.ProjectSurveySectionQuestionsList.find(x => x.QuestionId == AdditionalQuestionId)
                }
                OutcomeQuantitativeLogic.map(x => {
                        this.currentFilterSections.push({
                            Question: {
                                QuestionName: x.QuestionName,
                                QuestionId: x.QuestionId == 0 ? x.BeneficiaryTypeQstnID : x.QuestionId,
                                SectionORBeneficiary: x.QuestionId == 0 ? "Beneficiary" : "Section",

                            },
                            Section: {
                                SectionId: x.SectionId,
                                SectionName: x.SectionName,
                            },
                            Logic: {
                                ID: x.lstSurveyPrimeLogic.length && x.lstSurveyPrimeLogic[0].SurveyLogicPrime,
                                Type: x.lstSurveyPrimeLogic.length && x.lstSurveyPrimeLogic[0].SurveyLogicPrimeType
                            },
                            Answer: x.lstSurveyPrimeLogic.length && x.lstSurveyPrimeLogic[0].SurveyLogicPrimeAnswer,
                            condition: x.lstSurveyPrimeLogic.length && x.lstSurveyPrimeLogic[0].SurveyLogicCondition,
                            SurveyPrimeLogic: [{
                                SurveyLogicPrimeID: x.lstSurveyPrimeLogic.length && x.lstSurveyPrimeLogic[0].SurveyLogicPrime,
                                SurveyLogicPrime: x.lstSurveyPrimeLogic.length && x.lstSurveyPrimeLogic[0].SurveyLogicPrimeType,
                                SurveyLogicPrimeAnswer: x.lstSurveyPrimeLogic.length && x.lstSurveyPrimeLogic[0].SurveyLogicPrimeAnswer,
                                SurveyLogicCondition: x.lstSurveyPrimeLogic.length && x.lstSurveyPrimeLogic[0].SurveyLogicCondition
                            }]
                        })
                    
                })

            }
        },

        async setQuestionSelection(item, parent) {
            this.Loader = true
            this.QuestionType = 0
            this.LogicItemsPrime = this.LogicItemsPrimeCopy
            this.SurveyLogicPrimeAnswer = ''
            this.currentQuestion = null
            this.currentQuestionParent = null
            if (item) {
                this.currentQuestion = item
                this.currentQuestionParent = parent
                let { QuestionId, QuestionTypeID, SectionORBeneficiary, Type } = item
                // Update logic list
                if (QuestionId && Type) {
                    if (Type != 'Numeric' && Type != 'Date Picker') {
                        this.LogicItemsPrime = this.LogicItemsPrimeCopy.filter(x => x.IsNonNumeric)
                    } else {
                        this.LogicItemsPrime = this.LogicItemsPrimeCopy
                    }

                    if (['Single Choice', 'Multi-Choice', 'Dropdown', 'Likert Scale'].includes(Type)) {
                        this.QuestionType = 1
                        if (SectionORBeneficiary == "Beneficiary") {
                            try {
                                let { data } = await objManageProjectActivity.GetBeneficiaryAnswerOption(QuestionId)
                                if (!data || !data.length) {
                                    throw new Error('Invalid Response')
                                }
                                else {
                                    this.lstLogicAnswers = data
                                    this.PreLoader = false
                                }
                            } catch (error) {
                                console.error(error)
                                this.PreLoader = false
                            }
                        }
                        else {
                            try {
                                let { data } = await objManageProjectActivity.GetLogicAnswers(QuestionId)
                                if (!data || !data.length) {
                                    throw new Error('Invalid Response')
                                }
                                else {
                                    this.lstLogicAnswers = data
                                    this.PreLoader = false
                                }
                            } catch (error) {
                                console.error(error)
                                this.PreLoader = false
                            }
                        }
                    }

                    if (Type == 'Date Picker') {
                        this.QuestionType = 2
                    }

                    if (Type == 'Cascading Dropdown') {
                        this.QuestionType = 3

                        try {
                            let cascadingList = await objManageProjectActivity.GetSurveyCascadingList();
                            if (!cascadingList || !cascadingList.length) {
                                throw new Error(`Invalid Response - GetSurveyCascadingList`)
                            }
                            else {
                                // GetCascadingHeirarchyList(QuestionID, isBeneficiary)
                                this.CascadingQuestionOptions = await objManageProjectActivity.GetCascadingHeirarchyList(QuestionId, false)
                                if (!this.CascadingQuestionOptions || !this.CascadingQuestionOptions.length) {
                                    throw new Error(`Invalid Response - GetCascadingHeirarchyList`)
                                }
                                else {
                                    if (this.CascadingQuestionOptions != null) {
                                        for (var nCnt = 0; nCnt < this.CascadingQuestionOptions.length; nCnt++) {
                                            if (this.CascadingQuestionOptions[nCnt].OptionValue == "Country") {
                                                var lstCountry = result.data.filter(x => x.ItemTable == "Country");
                                                this.lstCountry = lstCountry.sort(function (a, b) { var x = a.Name < b.Name ? -1 : 1; return x; });
                                                // this.CascadingQuestionOptions[nCnt].CascadingList = this.lstCountry;

                                                if (this.CascadingQuestionOptions[0].OptionValue == "Country") {
                                                    this.CascadingQuestionOptions[0].CascadingList = this.lstCountry;
                                                } else {
                                                    this.CascadingQuestionOptions[nCnt].CascadingList = [];
                                                }
                                            }
                                            else if (this.CascadingQuestionOptions[nCnt].OptionValue == "States") {
                                                var lstStates = result.data.filter(x => x.ItemTable == "State");
                                                this.lstStates = lstStates.sort(function (a, b) { var x = a.Name < b.Name ? -1 : 1; return x; });

                                                if (this.CascadingQuestionOptions[0].OptionValue == "States") {
                                                    this.CascadingQuestionOptions[0].CascadingList = this.lstStates;
                                                } else {
                                                    this.CascadingQuestionOptions[nCnt].CascadingList = [];
                                                }
                                            }
                                            else if (this.CascadingQuestionOptions[nCnt].OptionValue == "District") {
                                                var lstDistrict = result.data.filter(x => x.ItemTable == "District");
                                                this.lstDistrict = lstDistrict.sort(function (a, b) { var x = a.Name < b.Name ? -1 : 1; return x; });

                                                if (this.CascadingQuestionOptions[0].OptionValue == "District") {
                                                    this.CascadingQuestionOptions[0].CascadingList = this.lstDistrict;
                                                } else {
                                                    this.CascadingQuestionOptions[nCnt].CascadingList = [];
                                                }
                                            }
                                            else if (this.CascadingQuestionOptions[nCnt].OptionValue == "SubDistrict") {
                                                var lstSubDistrict = result.data.filter(x => x.ItemTable == "SubDistrict");
                                                this.lstSubDistrict = lstSubDistrict.sort(function (a, b) { var x = a.Name < b.Name ? -1 : 1; return x; });

                                                if (this.CascadingQuestionOptions[0].OptionValue == "SubDistrict") {
                                                    this.CascadingQuestionOptions[0].CascadingList = this.lstSubDistrict;
                                                } else {
                                                    this.CascadingQuestionOptions[nCnt].CascadingList = [];
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        } catch (error) {
                            console.log(error)
                            this.$router.push({ name: "error" });
                        }
                    }

                    if (Type == 'Multi Line Text') {
                        this.QuestionType = 4
                    }
                }
                this.Loader = false
            }
        },

        setAdditionalQuestionSelection(item, parent) {
            this.PreLoader = true
            this.currentAdditionalQuestion = ''
            this.currentAdditionalQuestionParent = ''
            if (item) {
                this.currentAdditionalQuestion = item
                this.currentAdditionalQuestionParent = parent
            }
            this.PreLoader = false
        },

        addFilterSection() {
            if (this.currentFilterSections.length) {
                let data = this.currentFilterSections.find(x => x.FilterID == `${this.currentQuestionParent.SectionId}${this.currentQuestion.QuestionId}${this.SurveyLogicPrime.ID}${this.SurveyLogicPrimeAnswer}`)
                if (data) {
                    return
                }
            }

            let payload = {
                FilterID: `${this.currentQuestionParent.SectionId}${this.currentQuestion.QuestionId}${this.SurveyLogicPrime.ID}${this.SurveyLogicPrimeAnswer}`,
                Section: this.currentQuestionParent,
                Question: this.currentQuestion,
                Logic: this.LogicItemsPrime.find(x => x.ID == this.SurveyLogicPrime.ID),
                Answer: this.SurveyLogicPrimeAnswer,
                condition: this.lstConditions[0]
            }


            let primeLogic = [{
                SurveyLogicPrimeID: payload.Logic.ID,
                SurveyLogicPrime: payload.Logic.Type,
                SurveyLogicPrimeAnswer: payload.Answer,
                SurveyLogicCondition: payload.condition.OptionID,
            }]

            this.currentFilterSections.push({ ...payload, SurveyPrimeLogic: primeLogic })

            this.$on('conditionChanged', (val) => {
                let el = this.currentFilterSections.find(x => x.FilterID == val)
                el.SurveyPrimeLogic[0].SurveyLogicCondition = el.condition.OptionID
            })

            this.currentQuestion = {}
            this.currentQuestionParent = {}
            this.SurveyLogicPrime = 0
            this.SurveyLogicPrimeAnswer = ''
        },

        fnAggregateAnswers() {
            this.currentFilterSections.forEach(x => {
                let master
                this.masterSectionCollection.find(s => {
                    s.ProjectSurveySectionList &&
                        s.ProjectSurveySectionList.forEach(f => {
                            if (f.SectionId == x.Section.SectionId) {
                                master = s.SurveyId
                            }
                        })
                })
                if (master) {
                    this.OutPutQuantitativeLogicList.push({
                        QuestionId: x.Question.SectionORBeneficiary == "Beneficiary" ? 0 : x.Question.QuestionId,
                        QuestionName: x.Question.QuestionName,
                        SectionId: x.Section.SectionId,
                        SectionName: x.Section.SectionName,
                        SurveyId: master,
                        SurveyName: null,
                        SurveyPrimeLogic: x.SurveyPrimeLogic,
                        BeneficiaryTypeQstnID: x.Question.SectionORBeneficiary == "Beneficiary" ? x.Question.QuestionId : 0,
                    })
                }
            })
        },
        validateFields() {
            if (this.$refs.detailsForm.validate()) {
                if (this.currentFilterSections.length) {
                    this.fnAggregateAnswers();
                }
                this.fnCreateActivity()
            }
            else {
                this.snackBarMsg.message = "Please fill all mandatory details in details tab"
                this.snackBarMsg.value = true
                this.snackBarMsg.color = 'error'
            }

        },
        //function to destroy and close the dialog 
        unloadCreateOutput() {
            this.$emit('unloadDialog', true)
            this.$destroy()
        }
    },
    watch: {
        selectedSurveyList: function (v) {
            if (!v.length) {
                this.addSection = false
            }
        },

        tab: function (v) {
            if (v !== 'tab-payments') {
                this.OutPutQuantitativeLogicList = []
            }
        }
    },
}
</script>

<style scoped>
.close-btn {
    position: absolute;
    top: 5px;
    right: 5px;
}

#startDatePickerBtn {
    border-left: green 4px solid;
    border-radius: 4px;
    padding: 0px 5px;
}

#endDatePickerBtn {
    border-left: red 4px solid;
    border-radius: 4px;
    padding: 0px 5px;
}

#analysis-tabs-wrapper {
    background: #EBF5FF;
    border-radius: 8px;
    padding: 8px 24px;
}

.analysis-tab {
    background: #FEFEFE;
    box-shadow: 0px 0px 8px rgba(61, 126, 254, 0.149);
    border-radius: 8px;
}

.v-tab--active:hover::before {
    opacity: 0 !important;
}

.v-slide-group__content.v-tabs-bar__content {
    padding: 3px 0;
}

.section-headers-wrapper {
    background: #EBF5FF;
    color: #18426B;
    border-radius: 8px;
    padding: 3px 0;
}

.section-conditions-wrapper {
    background: #F6F6F6;
    border-radius: 8px;
    padding: 12px;
}

.section-conditions-subwrapper {
    background: #EBF5FF;
    border-radius: 8px;
    color: #15314E;
}

.month_table,
.month_th {
    border: 1px solid black;
}

.sticky-col {
    position: sticky;
    background-color: white;

}

.wrap-table {
    position: relative;
    overflow: auto;
    white-space: nowrap;
}

.td-text {
    font-size: 14px;
    width: 100px;
    text-align: center;
}

.td-text1 {
    font-size: 14px;
    width: 300px;
    text-align: center;
}

.td-text2 {
    font-size: 14px;
    width: 100px;
    text-align: center;
}

::v-deep table .v-text-field.v-text-field--enclosed input {
    text-align: center
}
</style>