using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SunidhiV2_0.Models
{
    public class ProjectActivity
    {
        public int ActivityId { get; set; }
        public int ParentActivityId { get; set; }
        public string ActivityName { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public double WeightagePercentage { get; set; }
        public string ActivityType { get; set; }
        public int SurveyId { get; set; }
        public int SurveySectionId { get; set; }
        public int BeneficiaryTypeQuestionID { get; set; }
        public int SurveyQuestionId { get; set; }
        public int SurveyResponseId { get; set; }
        public int SurveyLogic { get; set; }
        public string SurveyTarget { get; set; }
        public bool IsPaymentLinked { get; set; }
        public int PaymentLinkedBudget { get; set; }
        public int WorkflowId { get; set; }
        public string Workflow { get; set; }
        public int ProjectId { get; set; }
        public int Periodicity { get; set; }
        public int PeriodicityMonth { get; set; }
        public int PeriodicityMonthDay { get; set; }
        public int PeriodicityWeek { get; set; }
        public int PeriodicityMonthDateDay { get; set; }
        public string ReportingFrequencyName { get; set; }
        public DateTime PeriodicityOnceDate { get; set; }
        public List<Tags> ActivityTags { get; set; }
        public List<Tags> ExpenseTags { get; set; }
        public List<User> ExpenseTagsNotifyUsers { get; set; }
        public List<User> ActivityUsers { get; set; }
        public DateTime UpdatedDate { get; set; }
        public List<ProjectActivity> children { get; set; }
        public List<SurveyQuestion> SurveyQstnList { get; set; }
        public List<ProjectActivityMonthwiseData> lstProjectActivityMonthwiseData { get; set; }

        public string OutputName { get; set; }
        public string strStartDate { get; set; }
        public string strEndDate { get; set; }
        public string SubActivities { get; set; }
        public string Type { get; set; }
        public string  SurveyName {get;set;}
        public int Progress { get; set; }
        public double doubleProgress { get; set; }
        public bool multS { get; set; }
        public int BeneficiaryTypeID { get; set; }
        public List<OutPutQuantitativeLogic> OutPutQuantitativeLogic { get; set; }
        public List<OutPutQuantitativeLogic> OutPutQuantitativeFinancialLogic { get; set; }
        public int SubActivityCount { get; set; }
        public int Level { get; set; }
        public double SubActivityTotalWeightage { get; set; }
        public int AdditionalSurveyQuestionId { get; set; }
        public string AdditionalSectionId { get; set; }
        public int AdditionalQuestionId { get; set; }
        public string AutoGeneratedActivityId { get; set; }
        public bool? AdditionalQuestionType { get; set; }
        public bool? IsSubActivitiesAvailable { get; set; }
        public string UnitOfMeasure { get; set; }
        public List<OutPutCount> lstOutPutCount { get; set; }
        public string FinancialActivityType { get; set; }
        public string FinancialSurveyTarget { get; set; }
        public int FinancialSurveyLogic { get; set; }
        public int FinancialAdditionalSurveyId { get; set; }
        public int FinancialAdditionalSectionId { get; set; }
        public int FinancialAdditionalQuestionId { get; set; }
        public bool? FinancialAdditionalQuestionType { get; set; }
        public int UnitCost { get; set; }
        public double PhysicalActualValue { get; set; }
        public List<OutPutCount> lstOutPutCountPhysical { get; set; }
    }

    public class ActivityAttchments
    {
        public string ActivityTagsList { get; set; }
        public string ExpenseTagsList { get; set; }
        public string ExpenseTagsNotifyUsersList { get; set; }
        public string ActivityUsersList { get; set; }
    }

    public class NotifyExpenseTags
    {
        public string UserName { get; set; }
        public string ProjectName { get; set; }
        public string UserEmailId { get; set; }
    }

    public class DocumentviewModel
    {
        public int? ActivityId { get; set; }
        public string ActivityName { get; set; }
        public List<DocumentType> child_objects { get; set; }
    }
    public class DocumentType
    {
        public string ActivityId { get; set; }
        public string ActivityName { get; set; }
        public List<DocumentTypeClass> children { get; set; }
    }
    public class DocumentTypeClass
    {
        public string ActivityId { get; set; }
        public string ActivityName { get; set; }

    }
    public class DocumentModel
    {
        public string success { get; set; }
        public string message { get; set; }
        public List<DocumentType> data { get; set; }
    }
    public class DocumentResult
    {
        public int? ActivityId { get; set; }
        public string ActivityName { get; set; }

        public List<DocumentType> child_objects { get; set; }


    }

    public class Application1
    {
        public string ActivityId;
        public string ActivityName;
        public string children;
    }

    public class RootObject
    {
        public List<Application1> application;
    }

    public class Children
    {
        public int ActivityId;
        public string ActivityName;

    }
    public class Application
    {
        public IList<Children> children;
        public int ActivityId;
        public string ActivityName;

    }
    public class ActivityCount
    {
        public int TotalActivityCount;
        public int PendingActivityCount;

    }

    public class ActivityDataCollectionDetails
    {
        public int ID { get; set; }
        public int ActivityId { get; set; }
        public int SurveyId { get; set; }
        public int SectionId { get; set; }
        public int QuestionId { get; set; }
        public int BeneficiaryTypeID { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int BeneficiaryQuestionID { get; set; }
        public int SurveyAnswerType { get; set; }
        public int BenAnswerType { get; set; }
        public int SurveyLogicPrime { get; set; }
        public string SurveyLogicPrimeAnswer { get; set; }
        public string SurveyLogicPrimeType { get; set; }
        public int LogicCondition { get; set; }
        public int TypeofLogic { get; set; }
    }

    public class ActivitySurveyResponse
    {
        public int ResponseID { get; set; }
        public string Answer { get; set; }
        public int QuestionID { get; set; }
        public int SurveyID { get; set; }
        public int SyncTaskID { get; set; }
        public int SubmissionCount { get; set; }
        public DateTime CreatedDate { get; set; }
    }

    public class BeneficiaryResponse
    {
        public int ResponseID;
        public double Anwer;
        public int SurveyID;
        public DateTime CreatedDate;
        public string AnwerString;
        public int QuestionID;
    }

    public class OutPutCount
    {
        public string Answer { get; set; }
        public double AnswerSum { get; set; }
        public int ResponseCount { get; set; }
        public int SurveyID { get; set; }
        public DateTime CreatedDate { get; set; }
        public int ResponseId  { get; set; }
        public int QuestionID { get; set; }
        public int QuestionId { get; set; }
    }

    public class OutPutQuantitativeLogic
    {
        public int ID { get; set; }
        public int QuestionId { get; set; }
        public int SectionId { get; set; }
        public int SurveyId { get; set; }
        public int BeneficiaryTypeQstnID { get; set; }
        public string QuestionName { get; set; }
        public string SectionName { get; set; }
        public string SurveyName { get; set; }
        public List<SurveyPrimeLogic> lstSurveyPrimeLogic { get; set; }
        public int TypeofLogic { get; set; }
    }

    public enum OutPutLogicType
    {
        Count_of_Unique_Reponses = 1,
        Cumulative_Sum = 2,
        Equal_To = 3,
        Greater_Than = 4,
        Greater_Than_Or_Equal_To = 5,
        Less_Than = 6,
        Less_Than_Or_Equal_To = 7,
        Not_Equal_To = 8,
        increase_decrease = 9,
        change_over_time = 10,
        Average = 11
    }

    public class SurveyPrimeLogic
    {
        public int SurveyLogicPrime { get; set; }
        public string SurveyLogicPrimeAnswer { get; set; }
        public string SurveyLogicPrimeType { get; set; }
        public int BeneficiaryQuestionID { get; set; }
        public int SurveyLogicCondition { get; set; }
    }

    public class OutputPivotPresetData
    {
        public string PresetName { get; set; }
        public string PresetData { get; set; }
        public int SectionId { get; set; }
    }


    public class OutPutQuestionRSP
    {
        public double Answer { get; set; }
        public string AnswerString { get; set; }
        public int SyncTaskID { get; set; }
        public int SubmissionCount { get; set; }
        public int SurveyID { get; set; }
        public DateTime CreatedDate { get; set; }
        public int QuestionID { get; set; }
    }

    public class OutputOverview
    {
        public int ActivityID { get; set; }
        public int ActivityProgress { get; set; }
        public int CompletedCount { get; set; }
        public int PendingCount { get; set; }
        public int TotalCount { get; set; }
        public string LastExecutedDateTime { get; set; }
    }

    public class ProjectActivityMonthwiseData
    {
        public int ID { get; set; }
        public int ActivityId { get; set; }
        public double Target { get; set; }
        public double Budget { get; set; }
        public int ActMonth { get; set; }
        public int ActYear { get; set; }
    }

    public class ProjectActivityActualValue
    {
        public double PhysicalActualValue { get; set; }
        public double FinancialActualValue { get; set; }
    }

    public class ProjectOutputInitialData
    {
        public int SyncTaskID { get; set; }
        public int SubmissionCount { get; set; }
        public int ResponseID { get; set; }
        public int QuestionID { get; set; }
        public string Answer { get; set; }
        public int SurveyID { get; set; }
    }

    public class ProjectOutputBeneficiaryData
    {
        public int ResponseID { get; set; }
        public double TotalSum { get; set; }
    }
}



